<div align="center">
  <a href="https://github.com/montenegrotay">
  <img height="180em" src="https://github-readme-stats.vercel.app/api?username=montenegrotay&show_icons=true&theme=dracula&include_all_commits=true&count_private=true"/>
  <img height="180em" src="https://github-readme-stats.vercel.app/api/top-langs/?username=montenegrotay&layout=compact&langs_count=7&theme=dracula"/>


 ![Snake animation](https://github.com/montenegrotay/montenegrotay/blob/output/github-contribution-grid-snake.svg)![image](https://user-images.githubusercontent.com/111308396/191393820-f6886607-3bd1-40f9-98cc-efe99e9731a1.png)

</div>
